[package]
name = "fibonacci-calculator-in-rust"
version = "0.1.0"
authors = ["Grant-Work"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
